/**
 * Adapter stub generator for the `runInit` command.
 *
 * Takes scanned patterns and produces a TypeScript adapter file
 * with inline docs (from adapter JSDoc + README) and TODO placeholders.
 */
import type { ScannedPatterns } from "./scan-patterns.js";

/* ── Public API ───────────────────────────────────────────────────────── */

export function generateAdapterStub(patterns: ScannedPatterns): string {
  const sections: string[] = [];

  sections.push(header(patterns));
  sections.push(imports());
  sections.push("export const adapter = defineAdapter({");
  sections.push(styleMergerSection());
  if (patterns.themeRoots.size > 0) {
    sections.push(themeMappingSection(patterns));
  }
  sections.push(resolveValueSection(patterns));
  sections.push(resolveCallSection(patterns));
  sections.push(resolveSelectorSection(patterns));
  if (patterns.styledWrappers.size > 0) {
    sections.push(resolveBaseComponentSection(patterns));
  }
  sections.push(externalInterfaceSection());
  sections.push(useSxPropSection());
  if (patterns.hasUseTheme) {
    sections.push(themeHookSection());
  }
  sections.push("});\n");

  return sections.join("\n");
}

export function generateSummary(patterns: ScannedPatterns): string {
  const lines: string[] = [];

  lines.push(
    `Scanned ${patterns.filesScanned} files, found styled-components in ${patterns.filesWithStyledComponents} files.`,
  );
  lines.push("");

  if (patterns.themeRoots.size > 0) {
    lines.push(`Theme roots: ${sorted(patterns.themeRoots).join(", ")}`);
    lines.push(`  Unique theme paths (${patterns.themePaths.size}):`);
    for (const p of sorted(patterns.themePaths).slice(0, 20)) {
      lines.push(`    - theme.${p}`);
    }
    if (patterns.themePaths.size > 20) {
      lines.push(`    ... and ${patterns.themePaths.size - 20} more`);
    }
    if (patterns.hasIndexedThemeLookup) {
      lines.push("  Indexed lookups detected (e.g. theme.color[prop])");
    }
    lines.push("");
  }

  if (patterns.cssVariables.size > 0) {
    lines.push(`CSS variables (${patterns.cssVariables.size}):`);
    for (const v of sorted(patterns.cssVariables).slice(0, 15)) {
      lines.push(`  - ${v}`);
    }
    if (patterns.cssVariables.size > 15) {
      lines.push(`  ... and ${patterns.cssVariables.size - 15} more`);
    }
    lines.push("");
  }

  if (patterns.helperCalls.size > 0) {
    lines.push(`Helper functions called in interpolations (${patterns.helperCalls.size}):`);
    for (const [name, entry] of sortedEntries(patterns.helperCalls)) {
      lines.push(`  - ${name} (from "${entry.source}")`);
    }
    lines.push("");
  }

  if (patterns.selectorInterpolations.size > 0) {
    lines.push(`Selector interpolations (${patterns.selectorInterpolations.size}):`);
    for (const [name, entry] of sortedEntries(patterns.selectorInterpolations)) {
      lines.push(`  - \${${name}} (from "${entry.source}")`);
    }
    lines.push("");
  }

  if (patterns.styledWrappers.size > 0) {
    lines.push(`styled() wrappers around imported components (${patterns.styledWrappers.size}):`);
    for (const [name, entry] of sortedEntries(patterns.styledWrappers)) {
      lines.push(`  - styled(${name}) (from "${entry.source}")`);
    }
    lines.push("");
  }

  if (patterns.hasUseTheme) {
    lines.push("useTheme() hook usage detected");
    lines.push("");
  }

  lines.push("Adapter hooks needed:");
  lines.push(`  - resolveValue: ${describeResolveValueNeeds(patterns)}`);
  lines.push(
    `  - resolveCall: ${patterns.helperCalls.size > 0 ? `${patterns.helperCalls.size} helper(s)` : "none detected"}`,
  );
  lines.push(
    `  - resolveSelector: ${patterns.selectorInterpolations.size > 0 ? `${patterns.selectorInterpolations.size} selector(s)` : "none detected"}`,
  );
  lines.push("  - externalInterface: needs configuration");
  if (patterns.themeRoots.size > 0) {
    lines.push(`  - themeMapping: ${patterns.themeRoots.size} theme root(s)`);
  }
  if (patterns.hasUseTheme) {
    lines.push("  - themeHook: useTheme detected");
  }

  return lines.join("\n");
}

/* ── Section generators ───────────────────────────────────────────────── */

function header(patterns: ScannedPatterns): string {
  return `\
/**
 * Adapter for styled-components-to-stylex codemod.
 * Generated by runInit — scanned ${patterns.filesWithStyledComponents} files with styled-components.
 *
 * Search for TODO comments to fill in project-specific mappings.
 *
 * Migration steps:
 *   1. Define your theme tokens as StyleX variables (stylex.defineVars)
 *   2. Fill in the TODO sections below to map your theme/helpers/selectors
 *   3. Run: await runTransform({ files: "src/**/*.tsx", consumerPaths: "src/**/*.tsx", adapter })
 *   4. Verify output, fix warnings, iterate
 *
 * Docs: https://github.com/skovhus/styled-components-to-stylex-codemod#adapter
 */`;
}

function imports(): string {
  return `\
import { defineAdapter, runTransform } from "styled-components-to-stylex-codemod";
`;
}

function styleMergerSection(): string {
  return `\
  /**
   * Custom merger function for className/style combining.
   * When a component accepts external className/style props, the codemod needs to merge
   * StyleX styles with those external props. Provide a helper function for cleaner output,
   * or set to null for the verbose inline merging pattern.
   *
   * Expected signature:
   *   function merger(styles, className?, style?): { className?: string; style?: CSSProperties }
   */
  // TODO: Configure a styleMerger or set to null
  styleMerger: null,
`;
}

function themeMappingSection(patterns: ScannedPatterns): string {
  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * Declarative theme path → StyleX token mapping.`);
  lines.push(`   * Evaluated in order; first match wins.`);
  lines.push(`   *`);
  lines.push(`   * Pattern syntax (matched against the theme path, e.g. "color.labelBase"):`);
  lines.push(`   *   - Exact:   "color"    matches only ctx.path === "color"`);
  lines.push(
    `   *   - Prefix:  "color.*"  matches paths starting with "color." (e.g. "color.labelBase")`,
  );
  lines.push(`   *   - Wildcard: "*"       matches any path (catch-all)`);
  lines.push(`   *`);
  lines.push(`   * Entry types:`);
  lines.push(`   *   - { expr, imports }           → resolve to a StyleX expression`);
  lines.push(`   *   - { bail: true }              → skip (bail the file with a warning)`);
  lines.push(
    `   *   - { directional: [...] }      → expand shorthand (e.g. padding → paddingBlock + paddingInline)`,
  );
  lines.push(`   *`);
  lines.push(`   * Placeholders in \`expr\`:`);
  lines.push(
    `   *   - {property}    → remaining path after prefix (e.g. "labelBase" for "color.*" matching "color.labelBase")`,
  );
  lines.push(
    `   *   - {cssProperty} → camelCase CSS property (e.g. "backgroundColor" for "background-color")`,
  );
  lines.push(`   */`);
  lines.push(`  themeMapping: [`);

  for (const root of sorted(patterns.themeRoots)) {
    const rootPaths = [...patterns.themePaths].filter(
      (p) => p.startsWith(root + ".") || p === root,
    );
    lines.push(`    // theme.${root} — ${rootPaths.length} path(s) detected`);

    if (patterns.hasIndexedThemeLookup) {
      lines.push(
        `    // TODO: Uncomment if theme.${root}[dynamicProp] should use a prebuilt mixin map:`,
      );
      lines.push(`    // ["${root}", {`);
      lines.push(`    //   indexed: true, usage: "props", dynamicArgUsage: "memberAccess",`);
      lines.push(`    //   expr: "$${root}Mixins.{cssProperty}",`);
      lines.push(
        `    //   imports: [{ from: { kind: "specifier", value: "./${root}Mixins.stylex" }, names: [{ imported: "$${root}Mixins" }] }],`,
      );
      lines.push(`    // }],`);
    }

    if (rootPaths.length === 1 && rootPaths[0] === root) {
      lines.push(`    // TODO: Map theme.${root} to a StyleX token`);
      lines.push(
        `    ["${root}", { expr: "$tokens.${root}", imports: [{ from: { kind: "specifier", value: "./tokens.stylex" }, names: [{ imported: "$tokens" }] }] }],`,
      );
    } else {
      lines.push(`    // TODO: Map theme.${root}.* paths to StyleX tokens`);
      lines.push(
        `    ["${root}.*", { expr: "$${root}.{property}", imports: [{ from: { kind: "specifier", value: "./tokens.stylex" }, names: [{ imported: "$${root}" }] }] }],`,
      );
    }
    lines.push("");
  }

  lines.push("  ],");
  lines.push("");
  return lines.join("\n");
}

function resolveValueSection(patterns: ScannedPatterns): string {
  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * Resolve dynamic values in styled template literals to StyleX expressions.`);
  lines.push(`   * Called for:`);
  lines.push(
    `   *   - kind: "theme"         — props.theme.X.Y access (handled by themeMapping above if set)`,
  );
  lines.push(`   *   - kind: "cssVariable"   — var(--x) usage`);
  lines.push(`   *   - kind: "importedValue" — imported values used in interpolations`);
  lines.push(`   *`);
  lines.push(`   * Return { expr, imports } to provide a StyleX expression, or undefined to bail.`);
  lines.push(
    `   * For shorthand CSS properties, return { directional: [{ prop, expr, imports }] }.`,
  );
  lines.push(`   */`);
  lines.push("  resolveValue(ctx) {");

  if (patterns.themeRoots.size > 0) {
    lines.push("    // Theme lookups are handled by themeMapping above.");
    lines.push("    // Add fallback logic here if themeMapping doesn't cover all paths.");
  }

  if (patterns.cssVariables.size > 0) {
    const sample = sorted(patterns.cssVariables).slice(0, 5).join(", ");
    const ellipsis = patterns.cssVariables.size > 5 ? ", ..." : "";
    lines.push("");
    lines.push('    if (ctx.kind === "cssVariable") {');
    lines.push(`      // TODO: Map CSS variable names to StyleX variable tokens.`);
    lines.push(`      // Found ${patterns.cssVariables.size} variable(s): ${sample}${ellipsis}`);
    lines.push("      //");
    lines.push("      // Example: convert var(--primary-color) → $vars.primaryColor");
    lines.push(
      "      //   const camel = ctx.name.replace(/^--/, '').replace(/-([a-z])/g, (_, c) => c.toUpperCase());",
    );
    lines.push(
      `      //   return { expr: \`$vars.\${camel}\`, imports: [{ from: { kind: "specifier", value: "./vars.stylex" }, names: [{ imported: "$vars" }] }] };`,
    );
    lines.push("      return undefined;");
    lines.push("    }");
  }

  if (patterns.styledWrappers.size > 0) {
    lines.push("");
    lines.push('    if (ctx.kind === "importedValue") {');
    lines.push("      // TODO: Map imported styled-component values to StyleX equivalents.");
    lines.push("      return undefined;");
    lines.push("    }");
  }

  lines.push("");
  lines.push("    return undefined;");
  lines.push("  },");
  lines.push("");
  return lines.join("\n");
}

function resolveCallSection(patterns: ScannedPatterns): string {
  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * Resolve helper function calls found inside template interpolations.`);
  lines.push(`   * e.g. \${transitionSpeed("slow")} → transitionSpeedVars.slow`);
  lines.push(`   *`);
  lines.push(`   * The codemod infers how to use the result from context:`);
  lines.push(
    `   *   - With ctx.cssProperty (e.g. "color: \${helper()}") → CSS value in stylex.create()`,
  );
  lines.push(
    `   *   - Without ctx.cssProperty (e.g. "\${helper()}")     → StyleX style in stylex.props()`,
  );
  lines.push(`   *   - Override with usage: "create" | "props" if needed`);
  lines.push(`   *`);
  lines.push(`   * Return:`);
  lines.push(`   *   - { expr, imports }              → resolved expression`);
  lines.push(`   *   - { preserveRuntimeCall: true }  → keep original helper at runtime`);
  lines.push(`   *   - undefined                      → bail the file with a warning`);
  lines.push(`   */`);
  lines.push("  resolveCall(ctx) {");

  if (patterns.helperCalls.size > 0) {
    lines.push("    // Detected helpers:");
    for (const [name, entry] of sortedEntries(patterns.helperCalls)) {
      lines.push(`    //   ${name} (from "${entry.source}")`);
    }
    lines.push("    //");
    lines.push("    // TODO: Map each helper to a StyleX expression. Example:");
    lines.push('    // if (ctx.calleeImportedName === "transitionSpeed") {');
    lines.push('    //   const key = ctx.args[0]?.kind === "literal" ? ctx.args[0].value : null;');
    lines.push(
      '    //   return { expr: `$transitions.${key}`, imports: [{ from: { kind: "specifier", value: "./transitions.stylex" }, names: [{ imported: "$transitions" }] }] };',
    );
    lines.push("    // }");
  } else {
    lines.push("    // No helper function calls detected in template interpolations.");
  }

  lines.push("    return undefined;");
  lines.push("  },");
  lines.push("");
  return lines.join("\n");
}

function resolveSelectorSection(patterns: ScannedPatterns): string {
  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * Resolve interpolations used in CSS selector position.`);
  lines.push(`   * e.g. \${screenSize.phone} { ... } or &:\${highlight}`);
  lines.push(`   *`);
  lines.push(`   * Return:`);
  lines.push(`   *   - { kind: "media", expr, imports }              → media query`);
  lines.push(
    `   *   - { kind: "pseudoAlias", values, imports }      → pseudo-class (e.g. :hover, :active)`,
  );
  lines.push(
    `   *   - { kind: "pseudoExpand", expansions, imports } → pseudo-class with conditions`,
  );
  lines.push(`   *   - undefined                                     → bail the file`);
  lines.push(`   */`);
  lines.push("  resolveSelector(ctx) {");

  if (patterns.selectorInterpolations.size > 0) {
    lines.push("    // Detected selectors:");
    for (const [name, entry] of sortedEntries(patterns.selectorInterpolations)) {
      lines.push(`    //   \${${name}} (from "${entry.source}")`);
    }
    lines.push("    //");
    lines.push("    // TODO: Map selectors. Example for a media query helper:");
    lines.push('    // if (ctx.importedName === "screenSize" && ctx.path === "phone") {');
    lines.push('    //   return { kind: "media", expr: "(max-width: 768px)", imports: [] };');
    lines.push("    // }");
  } else {
    lines.push("    // No selector interpolations detected.");
  }

  lines.push("    return undefined;");
  lines.push("  },");
  lines.push("");
  return lines.join("\n");
}

function resolveBaseComponentSection(patterns: ScannedPatterns): string {
  const lines: string[] = [];
  lines.push(`  /**`);
  lines.push(`   * Optional: inline styled(ImportedComponent) into an intrinsic element.`);
  lines.push(`   * When a base component's behavior is purely CSS (e.g. <Flex>), the codemod can`);
  lines.push(
    `   * eliminate the runtime import and render a plain <div> with static StyleX styles.`,
  );
  lines.push(`   *`);
  lines.push(`   * ctx provides: importSource, importedName, staticProps (from .attrs() and JSX).`);
  lines.push(
    `   * Return { tagName, consumedProps, sx } to inline, or undefined to keep normal behavior.`,
  );
  lines.push(`   */`);
  lines.push("  resolveBaseComponent(ctx) {");
  lines.push("    // Detected styled() wrappers:");
  for (const [name, entry] of sortedEntries(patterns.styledWrappers)) {
    lines.push(`    //   styled(${name}) (from "${entry.source}")`);
  }
  lines.push("    //");
  lines.push("    // TODO: Inline base components whose behavior is purely CSS. Example:");
  lines.push('    // if (ctx.importedName === "Flex") {');
  lines.push('    //   const sx = { display: "flex" };');
  lines.push('    //   if (ctx.staticProps.column === true) sx.flexDirection = "column";');
  lines.push('    //   return { tagName: "div", consumedProps: ["column", "gap"], sx };');
  lines.push("    // }");
  lines.push("    return undefined;");
  lines.push("  },");
  lines.push("");
  return lines.join("\n");
}

function externalInterfaceSection(): string {
  return `\
  /**
   * Control which exported components accept external className/style/as props.
   *
   * "auto" scans consumer files (requires consumerPaths in runTransform) to detect
   * which components are wrapped with styled() or use the "as" prop. If prepass fails,
   * runTransform throws immediately — switch to a manual function to debug.
   *
   * For manual control, use a function:
   *   externalInterface(ctx) {
   *     // ctx: { filePath, componentName, exportName, isDefaultExport }
   *     return { styles: true, as: false, ref: false };
   *   }
   */
  externalInterface: "auto",
`;
}

function useSxPropSection(): string {
  return `\
  /**
   * Emit sx={...} JSX attributes instead of {...stylex.props(...)} spreads.
   * Requires @stylexjs/babel-plugin >=0.18 with sxPropName option enabled.
   * Produces shorter output: <div sx={styles.base} /> instead of <div {...stylex.props(styles.base)} />
   */
  useSxProp: false,
`;
}

function themeHookSection(): string {
  return `\
  /**
   * Theme hook used when wrappers need runtime theme access (e.g. for conditionals).
   * Update if your project uses a custom theme hook instead of styled-components' useTheme.
   */
  // TODO: Update if your theme hook has a different name or import source.
  themeHook: {
    functionName: "useTheme",
    importSource: { kind: "specifier", value: "styled-components" },
  },
`;
}

/* ── Helpers ──────────────────────────────────────────────────────────── */

function sorted(set: Set<string>): string[] {
  return [...set].sort();
}

function sortedEntries(
  map: Map<string, { source: string; importedName: string }>,
): [string, { source: string; importedName: string }][] {
  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

function describeResolveValueNeeds(patterns: ScannedPatterns): string {
  const parts: string[] = [];
  if (patterns.themeRoots.size > 0) {
    parts.push(`${patterns.themeRoots.size} theme root(s)`);
  }
  if (patterns.cssVariables.size > 0) {
    parts.push(`${patterns.cssVariables.size} CSS variable(s)`);
  }
  if (patterns.styledWrappers.size > 0) {
    parts.push(`${patterns.styledWrappers.size} imported value(s)`);
  }
  return parts.length > 0 ? parts.join(", ") : "none detected";
}
