/**
 * Shared opaque polymorphic helper type declarations.
 * Core concepts: substitute-based prop overriding and optional forwardedAs support.
 */

export const OPAQUE_POLYMORPHIC_HELPER_LINES = [
  "type __StylexCodemodFastOmit<T, K extends PropertyKey> = Omit<T, K>;",
  "type __StylexCodemodSubstitute<A, B> = __StylexCodemodFastOmit<A, keyof B> & B;",
  'type __StylexCodemodAsTargetProps<C extends React.ElementType> = __StylexCodemodFastOmit<React.ComponentPropsWithRef<C>, "className" | "style" | "as" | "forwardedAs">;',
  "type __StylexCodemodOpaquePolymorphicProps<BaseProps, C extends React.ElementType, ForwardedAsC extends React.ElementType | void = void> = NoInfer<[ForwardedAsC] extends [React.ElementType] ? __StylexCodemodSubstitute<BaseProps, __StylexCodemodSubstitute<__StylexCodemodAsTargetProps<ForwardedAsC>, __StylexCodemodAsTargetProps<C>>> : __StylexCodemodSubstitute<BaseProps, __StylexCodemodAsTargetProps<C>>> & { as?: C } & ([ForwardedAsC] extends [React.ElementType] ? { forwardedAs?: ForwardedAsC } : {});",
] as const;

export function buildOpaquePolymorphicHelpersDtsFileContent(): string {
  const indentedHelpers = OPAQUE_POLYMORPHIC_HELPER_LINES.map((line) => `  ${line}`);
  return [
    "// Generated by styled-components-to-stylex-codemod.",
    "// Keep this file checked in and included by tsconfig.",
    "export {};",
    "declare global {",
    ...indentedHelpers,
    "}",
    "",
  ].join("\n");
}
